### ISSUE TITLE
Missing Atomic Controllers - Not Synchronized with public repo  

### ISSUE THREAD

**Issue by hackz3r** [blackbotinc/Atomic-Red-Team-Intelligence-C2#8]
Example:
```
Directory: '///Atomic-Red-Team-Intelligence-C2/blackbot/core/wss/ttp/art/src/pwsh_cmd_ttp/discovery/T1482-4'
Traceback (most recent call last):
  File "///Atomic-Red-Team-Intelligence-C2/blackbot/core/wss/jobs.py", line 36, in get
    job_payload = job.payload()
  File "///Atomic-Red-Team-Intelligence-C2/blackbot/core/wss/job.py", line 21, in payload
    "source": self.module.payload(),
  File "///Atomic-Red-Team-Intelligence-C2/blackbot/core/wss/ttp/art/art_T1482-4.py", line 41, in payload
    with open(hybrid_script) as hybrid:
FileNotFoundError: [Errno 2] No such file or directory: '///Atomic-Red-Team-Intelligence-C2/blackbot/core/wss/ttp/art/src/pwsh_cmd_ttp/discovery/T1482-4'
```
Atomic Controllers Not Synchronized

**Comment by hackz3r** [comment]
confirmed  - logs indicate approximately 200+ atomics are not included.
```
2021-08-21 07:09:11,034 30944 MainThread - [DEBUG] loader.py: get_loadables - Loaded 474 atomic(s)
```
